/* Generated By:JavaCC: Do not edit this line. homeworkTreeConstants.java Version 5.0 */
package teste;

public interface homeworkTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPR = 1;
  public int JJTTERM = 2;
  public int JJTEXPRP = 3;
  public int JJTTERMP = 4;


  public String[] jjtNodeName = {
    "Start",
    "Expr",
    "Term",
    "ExprP",
    "TermP",
  };
}
/* JavaCC - OriginalChecksum=b58220996fcf09b79742c62229d7ec87 (do not edit this line) */
