/* Generated By:JJTree&JavaCC: Do not edit this line. hw4Constants.java */
package teste;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface hw4Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 4;
  /** RegularExpression Id. */
  int LF = 5;
  /** RegularExpression Id. */
  int MULT = 6;
  /** RegularExpression Id. */
  int DIV = 7;
  /** RegularExpression Id. */
  int SUM = 8;
  /** RegularExpression Id. */
  int SUB = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<INT>",
    "\"\\n\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
  };

}
