/* Generated By:JavaCC: Do not edit this line. hw4TreeConstants.java Version 5.0 */
package teste;

public interface hw4TreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPR = 1;
  public int JJTTERM = 2;
  public int JJTEXPRP = 3;
  public int JJTTERMP = 4;


  public String[] jjtNodeName = {
    "Start",
    "Expr",
    "Term",
    "ExprP",
    "TermP",
  };
}
/* JavaCC - OriginalChecksum=4e0deba6292719d24136d7b9f7ff619e (do not edit this line) */
