/* Generated By:JavaCC: Do not edit this line. hw2Constants.java */
package test;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface hw2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXPRESSION = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<EXPRESSION>",
  };

}
